DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""
from django.urls import path, include
from django.contrib import admin
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('', include("app.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
#アプリケーション側ルーティング設定

from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import forms, views
from datetime import datetime

app_name = "app"

urlpatterns = [
    path('', views.home, name = 'home'),
    path('home/', views.home, name = 'home'),
    path('about/', views.about, name = 'about'),
    path('contact/', views.contact, name = 'contact'),
    path('logout/', LogoutView.as_view(next_page = '/'), name = 'logout'),
    path('upload/', views.modelFormUpload, name = 'upload'),
    path('dotArt/', views.viewFilter, name = 'dotArt'),
    path('mosaic/', views.viewFilter, name = 'mosaic'),
    path('subColor/', views.viewFilter, name = 'subColor'),
    path('threshold/', views.viewFilter, name = 'threshold'),
    path('gauss/', views.viewFilter, name = 'gauss'),
    path('edge/', views.viewFilter, name = 'edge'),
    path('medianFilter/', views.viewFilter, name = 'medianFilter'),
    path('WBComic/', views.viewFilter, name = 'WBComic'),
    path('pencil/', views.viewFilter, name = 'pencil'),
    path('AIAnimeArt/', views.viewFilter, name = 'AIAnimeArt'),
    path('creatingColoringBook/', views.viewFilter, name = 'creatingColoringBook'),
    path('stylization/', views.viewFilter, name = 'stylization'),
    path('grayScale/', views.viewFilter, name = 'grayScale'),
#    path('edit/<int:num>', views.edit, name='edit'),
    path('login/',
        LoginView.as_view
        (
            template_name='app/login.html',
            authentication_form=forms.BootstrapAuthenticationForm,
            extra_context=
            {
                'title': 'Log in',
                'year' : datetime.now().year,
            }
        ),
        name='login'), 
]

app/templates/app/htmlComponents/(つかってない)formBase.html
<div class="jumbotron">
    <h1>{{ filterAlias }}</h1>
    <p>{{ explain }}</p>
    <!--<p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">写真を選ぶ&raquo;</a></p>-->   
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
       <!--{{ form.as_p }}--> 
        <input type="file" name = "avatar" value="写真を選択してください" onchange="OnFileSelect( this );" required/><!--multipleで複数ファイル-->
        <button type="submit" name = "create" id = "btn_create" style="display:none"></button>
    </form>
    
    <div id="pictureDisplay" >
        {% autoescape off %}
        {% load static %}
        <img src="{{ srcPath }}" id="srcImage" width="300" height="300" onerror="onErrorFilterImage( this )">
        <img src="{{ dstPath }}" id="dstImage" width="300" height="300" onerror="onErrorFilterImage( this )">        
        {% endautoescape %}
    </div>

    <div id="contolButtons">
        {% include 'app/htmlComponents/returnButton.html' %}
        {% include 'app/htmlComponents/downloadButton.html' %}
        {% load static %}
        <script src="{% static 'app/scripts/onErrorEvent.js' %}"></script>
    </div>
</div>

app/templates/app/htmlComponents/choiceButton.html
<div id="fileInputContainer">
    <label>
        画像を選択
        <input type="file" class="fileInput" name="avatar" value="写真を選択してください" onchange="OnFileSelect( this );" accept=".jpg, .jpeg, .png"/><!--multipleで複数ファイル-->
    </label>
</div>

app/templates/app/htmlComponents/controlButtons.html
<div id="contolButtons">
    {% include 'app/htmlComponents/downloadButton.html' %}
    {% include 'app/htmlComponents/returnButton.html' %}
    {% load static %}
    <script src="{% static 'app/scripts/onErrorEvent.js' %}"></script>
    <script src="{% static 'app/scripts/onChangeDstImage.js' %}"></script>
</div>

app/templates/app/htmlComponents/downloadButton.html
<div id="downloadButton">
    <a href="{{ dstPath }}" download="{{ dstFileName }}">画像をダウンロード</a>
</div>

app/templates/app/htmlComponents/formBase.html
<div class="jumbotron">
    <h1>{{ filterAlias }}</h1>
    <p>{{ explain }}</p>
    <!--<p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">写真を選ぶ&raquo;</a></p>-->   
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
       <!--{{ form.as_p }}--> 
        <input type="file" name = "avatar" value="写真を選択してください" onchange="OnFileSelect( this );" required/><!--multipleで複数ファイル-->
        <button type="submit" name = "create" id = "btn_create" style="display:none"></button>
    </form>
    
    <div id="pictureDisplay" >
        {% autoescape off %}
        {% load static %}
        <img src="{{ srcPath }}" id="srcImage" width="300" height="300" onerror="onErrorFilterImage( this )">
        <img src="{{ dstPath }}" id="dstImage" width="300" height="300" onerror="onErrorFilterImage( this )">        
        {% endautoescape %}
    </div>

    <div id="contolButtons">
        {% include 'app/htmlComponents/returnButton.html' %}
        {% include 'app/htmlComponents/downloadButton.html' %}
        {% load static %}
        <script src="{% static 'app/scripts/onErrorEvent.js' %}"></script>
    </div>
</div>

app/templates/app/htmlComponents/hiddenContents.html
<input type="text" name="recreate-srcPath" value="{{ srcPath }}" style="display:none">
<button type="submit" name="create" id="btn_create" style="display:none">
<button type="submit" name="recreate" id="btn_recreate" style="display:none">

app/templates/app/htmlComponents/pictureDisplay.html
<div id="pictureDisplay" >
    {% autoescape off %}
    {% load static %}
    <img src="{{ srcPath }}" id="srcImage" width="300" height="300" onerror="onErrorFilterImage( this )">
    <img src="{{ dstPath }}" id="dstImage" width="300" height="300" onerror="onErrorFilterImage( this )" onload="onChangeDstImage()">        
    {% endautoescape %}
</div>
{% include 'app/htmlComponents/waitIndicator.html' %}

app/templates/app/htmlComponents/recreateButton.html
<label>
    原画を再加工
    <button type="submit" name="recreate" style="display:none"  onclick="onClickRecreate();"></button>
</label>

app/templates/app/htmlComponents/returnButton.html
<div id="returnButton">
    <a href="{% url 'app:home' %}">トップページに戻る</a>
</div>

app/templates/app/htmlComponents/waitIndicator.html
<div id="waitIndicator" ></div>