DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""
from django.urls import path, include
from django.contrib import admin
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('', include("app.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
#アプリケーション側ルーティング設定

from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import forms, views
from datetime import datetime

app_name = "app"

urlpatterns = [
    path('', views.home, name = 'home'),
    path('home/', views.home, name = 'home'),
    path('about/', views.about, name = 'about'),
    path('contact/', views.contact, name = 'contact'),
    path('logout/', LogoutView.as_view(next_page = '/'), name = 'logout'),
    path('upload/', views.modelFormUpload, name = 'upload'),
    path('dotArt/', views.viewFilter, name = 'dotArt'),
    path('mosaic/', views.viewFilter, name = 'mosaic'),
    path('subColor/', views.viewFilter, name = 'subColor'),
    path('threshold/', views.viewFilter, name = 'threshold'),
    path('gauss/', views.viewFilter, name = 'gauss'),
    path('edge/', views.viewFilter, name = 'edge'),
    path('medianFilter/', views.viewFilter, name = 'medianFilter'),
    path('WBComic/', views.viewFilter, name = 'WBComic'),
    path('pencil/', views.viewFilter, name = 'pencil'),
    path('AIAnimeArt/', views.viewFilter, name = 'AIAnimeArt'),
    path('creatingColoringBook/', views.viewFilter, name = 'creatingColoringBook'),
    path('stylization/', views.viewFilter, name = 'stylization'),
    path('grayScale/', views.viewFilter, name = 'grayScale'),
#    path('edit/<int:num>', views.edit, name='edit'),
    path('login/',
        LoginView.as_view
        (
            template_name='app/login.html',
            authentication_form=forms.BootstrapAuthenticationForm,
            extra_context=
            {
                'title': 'Log in',
                'year' : datetime.now().year,
            }
        ),
        name='login'), 
]

app/templates/app/AIAnimeArt.html
{% extends "app/layout.html" %}
{% block myCss %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/mycss.css' %}" />
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>{{ filterAlias }}</h1>
    <p>{{ explain }}</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'app/htmlComponents/choiceButton.html' %}
        {% include 'app/htmlComponents/pictureDisplay.html' %}
        <!--S パラメータコンポーネント-->
        <!--E パラメータコンポーネント-->
        {% include 'app/htmlComponents/recreateButton.html' %}
        {% include 'app/htmlComponents/hiddenContents.html' %}
    </form>
</div>
{% include 'app/htmlComponents/controlButtons.html' %}
{% endblock %}

{% block scripts %}
{% load static %}
<script src="{% static 'app/scripts/buttonClickEvent.js' %}"></script>
{% endblock %}

app/templates/app/about.html
{% extends "app/layout.html" %}
{% block content %}
<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>
<p>Use this area to provide additional information.</p>
{% endblock %}

app/templates/app/dotArt.html
{% extends "app/layout.html" %}
{% block myCss %}
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>{{ filterAlias }}</h1>
    <p>{{ explain }}</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'app/htmlComponents/choiceButton.html' %}
        {% include 'app/htmlComponents/pictureDisplay.html' %}
        <!--S パラメータコンポーネント-->
        <p>
            <input type="number" name="dotNum" min="1" max="100" step="1" value={{ dotNum }} required>:モザイク度合い(%)
        </p>
        <p>
            <input type="number" name="colorNum" min="1" max="20" step="1" value={{ colorNum }} required>:色数
        </p>
        <!--E パラメータコンポーネント-->
        {% include 'app/htmlComponents/recreateButton.html' %}
        {% include 'app/htmlComponents/hiddenContents.html' %}
    </form>
</div>
{% include 'app/htmlComponents/controlButtons.html' %}
{% endblock %}

{% block scripts %}
{% load static %}
<script src="{% static 'app/scripts/buttonClickEvent.js' %}"></script>
{% endblock %}

app/templates/app/edge.html
{% extends "app/layout.html" %}
{% block myCss %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/mycss.css' %}" />
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>{{ filterAlias }}</h1>
    <p>{{ explain }}</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'app/htmlComponents/choiceButton.html' %}
        {% include 'app/htmlComponents/pictureDisplay.html' %}
        <!--S パラメータコンポーネント-->
        <!--E パラメータコンポーネント-->
        {% include 'app/htmlComponents/recreateButton.html' %}
        {% include 'app/htmlComponents/hiddenContents.html' %}
    </form>
</div>
{% include 'app/htmlComponents/controlButtons.html' %}
{% endblock %}

{% block scripts %}
{% load static %}
<script src="{% static 'app/scripts/buttonClickEvent.js' %}"></script>
{% endblock %}

app/templates/app/gauss.html
{% extends "app/layout.html" %}
{% block myCss %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/mycss.css' %}" />
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>{{ filterAlias }}</h1>
    <p>{{ explain }}</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'app/htmlComponents/choiceButton.html' %}
        {% include 'app/htmlComponents/pictureDisplay.html' %}
        <!--S パラメータコンポーネント-->
        <p>
            <input type="number" name="deviation" min="1" max="101" step="1" value={{ deviation }} required>:偏差（ユーザーに分かりずらい）
        </p>
        <p>
            <input type="number" name="kernel" min="1" max="101" step="2" value={{ kernel }} required>:カーネル数（ユーザーに分かりずらい）
        </p>
        <!--E パラメータコンポーネント-->
        {% include 'app/htmlComponents/recreateButton.html' %}
        {% include 'app/htmlComponents/hiddenContents.html' %}
    </form>
</div>
{% include 'app/htmlComponents/controlButtons.html' %}
{% endblock %}

{% block scripts %}
{% load static %}
<script src="{% static 'app/scripts/buttonClickEvent.js' %}"></script>
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}
{% block myCss %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/mycss.css' %}" />
{% endblock %}
{% block content %}
<div class="jumbotron">
    <h2>画像加工アプリ～巨匠～</h2>
    <div id="demoImage">
        <img src="{% static 'app/imgs/demoImage.png' %}">
    </div>
    <!--巨匠について-->
    <div id="aboutKyosho" >
        <p><br>画像加工アプリ～巨匠～について</br></p>
        <ul>
            <li>web上で画像加工が簡単にできるアプリです!</li>
            <li>数値を変えることによってあなた好みの画像へと変換することが可能です!</li>
            <li>ダウンロードボタンによって原画の大きさのまま画像ファイルをダウンロードすることが可能です!</li>
            <li>AIを用いた超解像技術も開発中!</li>
            <li>スマホからも変換可能!</li>
            <li>こんなフィルターが欲しいというご意見は”お問い合わせ”ページからお願いいたします!</li>
        </ul>
    </div>
    <h2>フィルター一覧</h2>
  <!-- 3カラム -->
    <section class="gridWrapper">
        <article class="grid">
            <div class="box">
                    <a href="{% url 'app:dotArt' %}">
                        <img src="{% static 'app/imgs/flower_dotArt.jpg' %}" width="290" height="290" alt="">
                        <p>ドット絵風</p>
                    </a>
            </div>
        </article>
        <article class="grid">
            <div class="box">
                    <a href="{% url 'app:subColor' %}">
                        <img src="{% static 'app/imgs/flower_subColor.jpg' %}" width="290" height="290" alt="">
                        <p>減色</p>
                    </a>
            </div>
        </article>
        <article class="grid">
            <div class="box">
                    <a href="{% url 'app:mosaic' %}">
                        <img src="{% static 'app/imgs/flower_mosaic.jpg' %}" width="290" height="290" alt="">
                        <p>モザイク</p>
                    </a>
            </div>
        </article>
    </section>
    <!-- / 3カラム -->

    <!-- 3カラム -->
    <section class="gridWrapper">
        <article class="grid">
            <div class="box">
                    <a href="{% url 'app:threshold' %}">
                        <img src="{% static 'app/imgs/flower_threshold.jpg' %}" width="290" height="290" alt="">
                        <p>二値化</p>
                    </a>
            </div>
        </article>
        <article class="grid">
            <div class="box">
                    <a href="{% url 'app:gauss' %}">
                        <img src="{% static 'app/imgs/flower_gauss.jpg' %}" width="290" height="290" alt="">
                        <p>ガウスぼかし</p>
                    </a>
            </div>
        </article>
        <article class="grid">
            <div class="box">
                    <a href="{% url 'app:edge' %}">
                        <img src="{% static 'app/imgs/flower_edge.jpg' %}" width="290" height="290" alt="">
                        <p>線画抽出</p>
                    </a>
            </div>
        </article>
    </section>
    <!-- / 3カラム -->

    <!-- 3カラム -->
    <section class="gridWrapper">
        <article class="grid">
            <div class="box">
                    <a href="{% url 'app:medianFilter' %}">
                        <img src="{% static 'app/imgs/flower_medianFilter.jpg' %}" width="290" height="290" alt="">
                        <p>メディアンフィルター</p>
                    </a>
            </div>
        </article>
        <article class="grid">
            <div class="box">
                <a href="{% url 'app:grayScale' %}">
                    <img src="{% static 'app/imgs/flower_grayScale.jpg' %}" width="290" height="290" alt="">
                    <p>グレースケール</p>
                </a>
            </div>
        </article>
        <article class="grid">
            <div class="box">
                    <a href="{% url 'app:pencil' %}">
                        <img src="{% static 'app/imgs/flower_pencil.jpg' %}" width="290" height="290" alt="">
                        <p>鉛筆風</p>
                    </a>
            </div>
        </article>
    </section>
    <!-- / 3カラム -->

    <!-- 3カラム -->
    <section class="gridWrapper">
        <article class="grid">
            <div class="box">
                    <a href="{% url 'app:AIAnimeArt' %}">
                        <img src="{% static 'app/imgs/flower_AIAnimation.jpg' %}" width="290" height="290" alt="">
                        <p>AIアニメ風</p>
                    </a>
            </div>
        </article>
        <article class="grid">
            <div class="box">
                    <a href="{% url 'app:creatingColoringBook' %}">
                        <img src="{% static 'app/imgs/flower_creatingColoringBook.jpg' %}" width="290" height="290" alt="">
                        <p>塗り絵化</p>
                    </a>
            </div>
        </article>
        <article class="grid">
            <div class="box">
                    <a href="{% url 'app:stylization' %}">
                        <img src="{% static 'app/imgs/flower_stylization.jpg' %}" width="290" height="290" alt="">
                        <p>水彩画風</p>
                    </a>
            </div>
        </article>
    </section>
    <!-- / 3カラム -->
</div>

{% endblock %}
{% block scripts %}
{% load static %}
{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>画像加工アプリ～巨匠～</title>
    {% load static %}
    <link rel="icon" href="{% static 'app/imgs/fabicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/mycss.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/waitIndicator.css' %}" />
    {% block myCss%}{% endblock %}
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">トップページに戻る</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'app:about' %}">アプリについて</a></li>
                    <li><a href="{% url 'app:contact' %}">お問い合わせ</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - kyosho</p>
        </footer>
    </div>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>

{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/login.html
{% extends "app/layout.html" %}
{% block content %}
<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/medianFilter.html
{% extends "app/layout.html" %}
{% block myCss %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/mycss.css' %}" />
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>{{ filterAlias }}</h1>
    <p>{{ explain }}</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'app/htmlComponents/choiceButton.html' %}
        {% include 'app/htmlComponents/pictureDisplay.html' %}
        <!--S パラメータコンポーネント-->
        <!--E パラメータコンポーネント-->
        {% include 'app/htmlComponents/recreateButton.html' %}
        {% include 'app/htmlComponents/hiddenContents.html' %}
    </form>
</div>
{% include 'app/htmlComponents/controlButtons.html' %}
{% endblock %}

{% block scripts %}
{% load static %}
<script src="{% static 'app/scripts/buttonClickEvent.js' %}"></script>
{% endblock %}

app/templates/app/modelFormUpload.html
{% extends "app/layout.html" %}
{% block content %}
<!--enctypeを指定しないとうまくアップロードできない-->
<h1>Upload.</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
{% endblock %}
{% block scripts %}
{% load static %}
<script src="{% static 'app/scripts/buttonClickEvent.js' %}"></script>
{% endblock %}

app/templates/app/pencil.html
{% extends "app/layout.html" %}
{% block myCss %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/mycss.css' %}" />
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>{{ filterAlias }}</h1>
    <p>{{ explain }}</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'app/htmlComponents/choiceButton.html' %}
        {% include 'app/htmlComponents/pictureDisplay.html' %}
        <!--S パラメータコンポーネント-->
        <!--E パラメータコンポーネント-->
        {% include 'app/htmlComponents/recreateButton.html' %}
        {% include 'app/htmlComponents/hiddenContents.html' %}
    </form>
</div>
{% include 'app/htmlComponents/controlButtons.html' %}
{% endblock %}

{% block scripts %}
{% load static %}
<script src="{% static 'app/scripts/buttonClickEvent.js' %}"></script>
{% endblock %}

app/templates/app/subColor.html
{% extends "app/layout.html" %}
{% block myCss %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/mycss.css' %}" />
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>{{ filterAlias }}</h1>
    <p>{{ explain }}</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'app/htmlComponents/choiceButton.html' %}
        {% include 'app/htmlComponents/pictureDisplay.html' %}
        <!--S パラメータコンポーネント-->
        <p>
            <input type="number" name="colorNum" min="1" max="100" step="1" value={{ colorNum }} required>:色数
        </p>
        <!--E パラメータコンポーネント-->
        {% include 'app/htmlComponents/recreateButton.html' %}
        {% include 'app/htmlComponents/hiddenContents.html' %}
    </form>
</div>
{% include 'app/htmlComponents/controlButtons.html' %}
{% endblock %}

{% block scripts %}
{% load static %}
<script src="{% static 'app/scripts/buttonClickEvent.js' %}"></script>
{% endblock %}

app/templates/app/threshold.html
{% extends "app/layout.html" %}
{% block myCss %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/mycss.css' %}" />
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>{{ filterAlias }}</h1>
    <p>{{ explain }}</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'app/htmlComponents/choiceButton.html' %}
        {% include 'app/htmlComponents/pictureDisplay.html' %}
        <!--S パラメータコンポーネント-->
        <!--E パラメータコンポーネント-->
        {% include 'app/htmlComponents/recreateButton.html' %}
        {% include 'app/htmlComponents/hiddenContents.html' %}
    </form>
</div>
{% include 'app/htmlComponents/controlButtons.html' %}
{% endblock %}

{% block scripts %}
{% load static %}
<script src="{% static 'app/scripts/buttonClickEvent.js' %}"></script>
{% endblock %}

app/templates/app/各フィルターのベースになるページ.html
{% extends "app/layout.html" %}
{% block myCss %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/mycss.css' %}" />
{% endblock %}
{% block content %}
<div class="jumbotron">
    <h1>画像加工～巨匠～</h1>
    <p>豊富なフィルターであなたの写真を加工します。</p>
    <!--<p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">写真を選ぶ&raquo;</a></p>-->   

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
       <!--{{ form.as_p }}--> 
        <input type="file" name = "avatar" value="写真を選択してください" onchange="OnFileSelect( this );" required/><!--multipleで複数ファイル-->
        <button type="submit" name = "gray" id = "btn_gray">グレー変換</button>
        <button type="submit" name = "threshold" id = "btn_threshold">二値化</button>
        <button type="submit" name = "mosaic" id = "btn_mosaic">モザイク</button>
        <button type="submit" name = "subColor" id = "btn_subColor">減色</button>
        <button type="submit" name = "dotArt" id = "btn_dotArt">ドット絵風</button>
        <input type="submit">
    </form>
    <ul id="ID001" ></ul>
    <img src="{{ dstPath }}" width="300" height="300"/>
<!--
    <tr>
        <td>{{ obj.description }}</td>
        <td><img src="{{ obj.photo.url }}" width="300" height="300"/></td>
        <td><img src="{{ obj.filterPhoto.url }}" width="300" height="300"/></td>
    <tr>
-->
</div>
{% endblock %}
{% block scripts %}
{% load static %}
<script src="{% static 'app/scripts/buttonClickEvent.js' %}"></script>
{% endblock %}